### ISSUE TITLE
Style console's "Navigation marker" 

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/ux#16]
In the console, if you have the `Persist Logs` input checked, when you navigate to another page, we display what we call a `Navigation Marker`: 

<img width="836" alt="image" src="https://user-images.githubusercontent.com/578107/44512714-bd4f8300-a6bb-11e8-9792-4526c6b3e00f.png">

---

As you can see, it does not really stand out of the rest of the messages, and it would be nice to make it easier to spot.

This might be with: 
- an icon
- borders
- different text color
- a combination of those
- something else ?

**Comment by nchevobbe** [comment]
This is also tracked in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1317076), but let's have the design conversation here.

**Comment by fvsch** [comment]
My first idea would be to make it a info log, which is a bit more distinctive.
But from the Bugzilla bug it seems it should not be filterable, so not a "log" and not an "info" or "warning" type. Then it should probably have a different style.

Borders might be doable, it represents a "break" in context, but they would be easier to do cleanly if we had a console row setup like Chrome:

```
1px   ----------------- 
18px  Row content
1px   -----------------
18px  Next row content
1px   -----------------
```

This setup helps avoid double (2px) borders when you have two logs of the same type with borders.

Leaving borders aside for now, here are a few tests:

## Backgrounds

Grey-10 and Grey-20. (Similarly for the dark theme, Grey-80 or Grey-70, since the default for logs is Grey-90.)

<img width="599" alt="Nav log with Grey-10 background" src="https://user-images.githubusercontent.com/243601/44584531-8788c800-a7a9-11e8-9204-0dce9df8b499.png">

<img width="599" alt="Nav log with Grey-20 background" src="https://user-images.githubusercontent.com/243601/44584532-8788c800-a7a9-11e8-83a6-0a6b78430e47.png">

## Colors

Tried some Photon blue and purple, because they might suggest "navigation".

<img width="599" alt="Nav log with blue text" src="https://user-images.githubusercontent.com/243601/44584598-ccacfa00-a7a9-11e8-87de-43e26d98a517.png">

<img width="599" alt="Nav log with purple text" src="https://user-images.githubusercontent.com/243601/44584599-ccacfa00-a7a9-11e8-81e3-1ebf980be3a5.png">

## Icon

Used the following Photon icons:

- [Globe](https://design.firefox.com/icons/viewer/#globe)
- [History](https://design.firefox.com/icons/viewer/#history)
- [Link](https://design.firefox.com/icons/viewer/#link)

<img width="599" alt="Nav log with globe icon" src="https://user-images.githubusercontent.com/243601/44584674-07169700-a7aa-11e8-80df-b97858e6faaf.png">

![Nav log with history icon](https://user-images.githubusercontent.com/243601/44585165-b738cf80-a7ab-11e8-82e6-0b28c847fbfe.png)

![Nav log with link icon](https://user-images.githubusercontent.com/243601/44585167-b7d16600-a7ab-11e8-81f8-9ed3417ffa83.png)

**Comment by fvsch** [comment]
I believe Globe or History icon and a subtle Grey-10 background could work nicely.

**Comment by bwinton** [comment]
I feel like globe suggests navigation more than history, which makes me think of debugging for some reason...  Also, what would it look like if we used the favicon of the site we navigated to?

**Comment by fvsch** [comment]
Console icons are on a 12x12 canvas, and often only take the 10x10 pixel center area of that canvas. I think if we put a 16x16 favicon in that gutter it might look a bit out of place.

**Comment by nchevobbe** [comment]
Trying with the `--object-color` var looks nice too: 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/578107/46149224-23ef3000-c26a-11e8-9756-3fe866a05545.png">

<img width="777" alt="image" src="https://user-images.githubusercontent.com/578107/46149197-1639aa80-c26a-11e8-88cc-3f80aade2baa.png">

---

or with the same one used for the location: 

<img width="780" alt="image" src="https://user-images.githubusercontent.com/578107/46149312-4f721a80-c26a-11e8-9bf5-258bc1b55dc5.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/578107/46149327-5ac54600-c26a-11e8-9ce9-fdff21cc198d.png">

---
And we could also apply the same color to the border: 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/578107/46149432-9b24c400-c26a-11e8-9900-e47fbc9279c3.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/578107/46149404-89432100-c26a-11e8-9ca7-73742c218b04.png">

**Comment by savvysiddharth** [comment]
> And we could also apply the same color to the border:
> 
> <img alt="image" width="783" src="https://user-images.githubusercontent.com/578107/46149432-9b24c400-c26a-11e8-9900-e47fbc9279c3.png">
> 
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/578107/46149404-89432100-c26a-11e8-9ca7-73742c218b04.png">

yeah this one looks nice :+1:

**Comment by fvsch** [comment]
I like it so far.
Color: I prefer the lighter blue (`--object-color`) over the darker blue, especially in the dark theme.

The part I'm not sure about is the blue-vs-gray border.

- For: it clearly signals a change in context (which means that the previous JavaScript execution context is mostly gone).
- Against: it's not consistent with DevTools' use of subtle borders.

So I would probably keep the subtle border color.
Pinging @violasong. Any of these variants look better to you?

**Comment by violasong** [comment]
Sorry for the delay in responding to this! This is all great work - I love the globe icon and use of --object-color. 

As for the lines, I would also keep the gray over the blue - I feel the blue lines start to get overpowering and are a bit too different in style. However, in dark mode, those gray lines do seem very subtle against the gray of the console. If we need those rows to be more prominent, I'd try either a stronger gray line color or subtle background as Florens suggested.

**Comment by nchevobbe** [comment]
got it, thanks for your input @violasong !

**Comment by fvsch** [comment]
This landed in Nightly, but I'm unsure about two details:

1. When the first item is a navigation log, we end up with a double border. This can be fixed in CSS by excluding `:first-child` items or resetting their top border.
2. It feels a bit strange to have this slightly darker border color in between the lighter splitters. I would rather use the normal splitter color rather than the "emphasized" one.

![Navigation markers screenshot](https://user-images.githubusercontent.com/243601/47292915-cd76d680-d608-11e8-961e-08a814cbc679.png)

**Comment by nchevobbe** [comment]
I created https://bugzilla.mozilla.org/show_bug.cgi?id=1512621 for the double border thing.

**Comment by fvsch** [comment]
Closing since we shipped the new style.
